with-expecter: true
packages:
  # internal
  github.com/openmfp/extension-content-operator/pkg/validation:
    config:
      dir: pkg/validation/mocks
      outpkg: mocks
    interfaces:
      ExtensionConfiguration:
        config:
          mockname: ExtensionConfiguration

  # external
  net/http:
    config:
      dir: pkg/validation/mocks
      outpkg: mocks
    interfaces:
      ResponseWriter:
        config:
          mockname: ResponseWriter