// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Authentication struct {
	Type      *string               `json:"type,omitempty"`
	SecretRef *LocalObjectReference `json:"secretRef,omitempty"`
}

type ContentConfiguration struct {
	Spec   *ContentConfigurationSpec   `json:"spec,omitempty"`
	Status *ContentConfigurationStatus `json:"status,omitempty"`
}

type ContentConfigurationSpec struct {
	RemoteConfiguration *RemoteConfiguration `json:"remoteConfiguration,omitempty"`
	InlineConfiguration *InlineConfiguration `json:"inlineConfiguration,omitempty"`
}

type ContentConfigurationStatus struct {
	ConfigurationResult *string `json:"configurationResult,omitempty"`
}

type InlineConfiguration struct {
	ContentType string `json:"contentType"`
	Content     string `json:"content"`
}

type LocalObjectReference struct {
	Name string `json:"name"`
}

type Query struct {
}

type RemoteConfiguration struct {
	ContentType    string          `json:"contentType"`
	URL            string          `json:"url"`
	InternalURL    *string         `json:"internalUrl,omitempty"`
	Authentication *Authentication `json:"authentication,omitempty"`
}
