apiVersion: core.openmfp.io/v1alpha1
kind: ContentConfiguration
metadata:
  name: remote
  namespace: default
spec:
  remoteConfiguration:
    authentication:
      secretRef:
        name: "your-secret-name"
      type: "Bearer"
    url: "https://raw.githubusercontent.com/openmfp/portal/main/backend/src/provider-jsons/service-provider1.json?token=GHSAT0AAAAAACSINQKM7WYNKNN3IRSMJTAAZS65NRA"