# This workflow performs static code analysis of your Kubernetes object definitions
# using kube-score and kube-linter tools.
name: Kube Checks

on:
  push:

jobs:
  kube-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: kube-score check
        uses: piraces/kube-score-ga@v0.1.3
        with:
          args: score ${{ inputs.kube_score_target }}

      - name: kube-linter
        uses: stackrox/kube-linter-action@v1.0.5
        with:
          args: lint ${{ inputs.kube_score_target }}

