# This workflow performs static code analysis of your Kubernetes object definitions
# using kube-score and kube-linter tools.
name: Kube Checks

on:
  push:

jobs:
  kube-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: kube-score install
        uses: yokawasa/action-setup-kube-tools@v0.11.1
        with:
          kube-score: 'v1.18.0'

      - name: kube-score run
        if: always()
        run: |
          kube-score score ./config/**/*.y*ml

      - name: kube-linter
        if: always()
        uses: stackrox/kube-linter-action@v1.0.5
        with:
          directory: "./"
