name: ci
on: [push]

jobs:
  pipe:
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    uses: openmfp/gha/.github/workflows/pipeline-golang-app.yml@fix-rollback-with-big-runner
    secrets: inherit
    with:
      imageTagName: ghcr.io/openmfp/extension-content-operator
      useTask: true
      useLocalCoverageConfig: true
